Author: Shruti Gupta<br>
File Name: shruti gupta - assignment 3 - week 3<br>
Date: 16/03/2019

In [1]:
import numpy as np

***Question 1***<br>
1.Create a rank 2 numpy array of random integers and print:<br>
    a) shape,size and dimensions of the array <br>
    b) number of odd and even<br>
integers in the array

In [2]:
#Q1
#creating a rank 2 array
arr = np.array([[13,22,34], [42,54,62], [71,28,19], [14,13,12]])
arr

array([[13, 22, 34],
       [42, 54, 62],
       [71, 28, 19],
       [14, 13, 12]])

In [3]:
#array dimension
arr.ndim

2

In [4]:
#array shape
arr.shape

(4, 3)

In [5]:
#array size
arr.size

12

In [22]:
#number of odds and even in the array
oddnum=0
evennum=0
for i in range(0,4):
    for j in range(0,3):
        if arr[i][j]%2==0:
            evennum+=1
        else:
            oddnum+=1
print("the number of odds in the array are: ",oddnum)
print("the number of evens in the array are: ",evennum)

the number of odds in the array are:  4
the number of evens in the array are:  8


***Question 2***<br>
2.Create a (3X3) numpy array with values ranging from 1 to 9.

In [29]:
#q2
#creating a (3X3) numpay array
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

***Question 3***<br>
3.Create a (5X5) random numpy array and print the numbers from the array which are greater than average value of the array.
<br>Hint: Use np.where() function

In [51]:
#q3
#creating a (5X5) random array
arr3 = np.random.randint(20,size=(5,5))
arr3
np.where(arr3>arr3.mean(axis = 0),arr3,arr3.mean(axis = 0))

array([[19. ,  8. ,  9. ,  7.4, 17. ],
       [10.4, 13. , 14. , 19. , 18. ],
       [15. ,  6.8,  9. ,  7.4, 11.6],
       [16. ,  6.8, 18. ,  7.4, 11.6],
       [10.4,  6.8,  9. ,  7.4, 11.6]])

***Question 4***<br>
4.Given an array of random integers:<br>
arr1 = np.random.randint(50,size=(10,10))<br>
Find out : <br>
a) row wise and column wise mean <br>
b) row wise and column wise max and min values <br>
c) Variance and Standard Deviation of the array.

In [67]:
arr1 = np.random.randint(50,size=(10,10))
arr1

array([[ 1, 39, 16, 46,  6, 34, 43, 46, 46, 44],
       [33, 20, 29, 16, 18, 49,  5, 31, 21, 46],
       [32, 25, 32, 21, 34, 24, 30, 23, 35, 44],
       [44, 37, 44, 45, 41, 46, 12,  8,  0,  7],
       [ 6, 27, 40, 12, 12, 33, 34, 28, 28, 46],
       [29, 35,  4, 15, 26, 38, 22, 30, 22, 32],
       [ 3, 19, 12, 15,  4, 16,  4,  5, 12, 42],
       [20, 16, 14, 44, 37, 19,  9, 36, 16, 33],
       [13,  2,  8, 49, 36, 24,  6, 39, 10, 46],
       [13, 25,  2, 48, 16, 42, 18,  4,  7, 34]])

In [68]:
arr1.mean(axis=0) #row wise mean

array([19.4, 24.5, 20.1, 31.1, 23. , 32.5, 18.3, 25. , 19.7, 37.4])

In [69]:
arr1.mean(axis=1) #column wise mean

array([32.1, 26.8, 30. , 28.4, 26.6, 25.3, 13.2, 24.4, 23.3, 20.9])

In [71]:
#min and max row wise
arrmax = np.amax(arr1,axis=0) 
arrmin = np.amin(arr1,axis=0)
print(arrmax," ",arrmin)

[44 39 44 49 41 49 43 46 46 46]   [ 1  2  2 12  4 16  4  4  0  7]


In [72]:
#min and max column wise
arrmax = np.amax(arr1,axis=1) 
arrmin = np.amin(arr1,axis=1)
print(arrmax," ",arrmin)

[46 49 44 46 46 38 42 44 49 48]   [ 1  5 21  0  6  4  3  9  2  2]


***Question 5***<br>
5.Given two matrices:<br>
arr1 = np.matrix([[4,5],[7,3]])<br>
arr2 = np.matrix([[2,3],[8,9]])<br>

Find out the matrix multiplication of the above two matrices without using numpy function and then verify your answer using np.dot(arr1,arr2) function

In [75]:
#q5
#creating the matrix
arr1 = np.matrix([[4,5],[7,3]])
arr2 = np.matrix([[2,3],[8,9]])
print(arr1,"\n",arr2)

[[4 5]
 [7 3]] 
 [[2 3]
 [8 9]]


In [76]:
#the multiplication without the numpy function
arr1 * arr2

matrix([[48, 57],
        [38, 48]])

In [77]:
#confirming the values
np.dot(arr1,arr2)

matrix([[48, 57],
        [38, 48]])